/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

import volvis.RaycastMode;
import volvis.RaycastRenderer;
import volvis.TFColor;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;

/**
 *
 * @author michel
 */
public class RaycastRendererPanel extends JPanel {

    RaycastRenderer renderer;
    TransferFunctionEditor tfEditor = null;
    TransferFunction2DEditor tfEditor2D = null;

    /**
     * Creates new form RaycastRendererPanel
     */
    public RaycastRendererPanel(RaycastRenderer renderer) {
        initComponents();
        this.renderer = renderer;
        this.colorButton.setBackground(new Color(255, 255, 0));
        this.colorButton1.setBackground(new Color(255, 255, 0));
    }

    public void setSpeedLabel(String text) {
        renderingSpeedLabel.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        buttonGroup2 = new ButtonGroup();
        jLabel1 = new JLabel();
        renderingSpeedLabel = new JLabel();
        slicerButton = new JRadioButton();
        mipButton = new JRadioButton();
        compositingButton = new JRadioButton();
        tf2dButton = new JRadioButton();
        shadingCheckbox = new JCheckBox();
        isoSurfaceButton = new JRadioButton();
        jLabel2 = new JLabel();
        IsovalueTextBox = new JTextField();
        jLabel3 = new JLabel();
        colorButton = new JButton();
        cuttingPlaneCheckbox = new JCheckBox();
        jLabel4 = new JLabel();
        slicerButton2 = new JRadioButton();
        mipButton2 = new JRadioButton();
        compositingButton2 = new JRadioButton();
        isosurfaceButton2 = new JRadioButton();
        jLabel5 = new JLabel();
        IsovalueTextBox1 = new JTextField();
        jLabel6 = new JLabel();
        colorButton1 = new JButton();
        transferFunction2dButton = new JRadioButton();
        jLabel7 = new JLabel();

        jLabel1.setText("Rendering time (ms):");

        renderingSpeedLabel.setText("jLabel2");

        buttonGroup1.add(slicerButton);
        slicerButton.setSelected(true);
        slicerButton.setText("Slicer");
        slicerButton.addActionListener(this::slicerButtonActionPerformed);

        buttonGroup1.add(mipButton);
        mipButton.setText("MIP");
        mipButton.addActionListener(this::mipButtonActionPerformed);

        buttonGroup1.add(compositingButton);
        compositingButton.setText("Compositing");
        compositingButton.addActionListener(this::compositingButtonActionPerformed);

        buttonGroup1.add(tf2dButton);
        tf2dButton.setText("2D Transfer function");
        tf2dButton.addActionListener(this::tf2dButtonActionPerformed);

        shadingCheckbox.setText("Volume shading");
        shadingCheckbox.addActionListener(this::shadingCheckboxActionPerformed);

        buttonGroup1.add(isoSurfaceButton);
        isoSurfaceButton.setText("Isosurface");
        isoSurfaceButton.addActionListener(this::isoSurfaceButtonActionPerformed);

        jLabel2.setText("Isovalue:");

        IsovalueTextBox.setText("95.0");
        IsovalueTextBox.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        IsovalueTextBox.addActionListener(this::IsovalueTextBoxActionPerformed);

        jLabel3.setText("Color:");

        colorButton.addActionListener(this::colorButtonActionPerformed);

        cuttingPlaneCheckbox.setText("Cutting plane");
        cuttingPlaneCheckbox.addActionListener(this::cuttingPlaneCheckboxActionPerformed);

        jLabel4.setText("Back mode");
        jLabel4.setEnabled(cuttingPlaneCheckbox.isEnabled());

        buttonGroup2.add(slicerButton2);
        slicerButton2.setSelected(true);
        slicerButton2.setText("Invisible");
        slicerButton2.setEnabled(cuttingPlaneCheckbox.isSelected());
        slicerButton2.addActionListener(this::slicerButton2ActionPerformed);

        buttonGroup2.add(mipButton2);
        mipButton2.setText("MIP");
        mipButton2.setEnabled(cuttingPlaneCheckbox.isSelected());
        mipButton2.addActionListener(this::mipButton2ActionPerformed);

        buttonGroup2.add(compositingButton2);
        compositingButton2.setText("Compositing");
        compositingButton2.setEnabled(cuttingPlaneCheckbox.isSelected());
        compositingButton2.addActionListener(this::compositingButton2ActionPerformed);

        buttonGroup2.add(isosurfaceButton2);
        isosurfaceButton2.setText("Isosurface");
        isosurfaceButton2.setEnabled(cuttingPlaneCheckbox.isSelected());
        isosurfaceButton2.addActionListener(this::isosurfaceButton2ActionPerformed);

        jLabel5.setText("Isovalue:");

        IsovalueTextBox1.setText("95.0");
        IsovalueTextBox1.setCursor(new Cursor(Cursor.TEXT_CURSOR));
        IsovalueTextBox1.setEnabled(cuttingPlaneCheckbox.isSelected());
        IsovalueTextBox1.addActionListener(this::IsovalueTextBox1ActionPerformed);

        jLabel6.setText("Color:");

        colorButton1.setEnabled(cuttingPlaneCheckbox.isSelected());
        colorButton1.addActionListener(this::colorButton1ActionPerformed);

        buttonGroup2.add(transferFunction2dButton);
        transferFunction2dButton.setText("2D Transfer function");
        transferFunction2dButton.setEnabled(cuttingPlaneCheckbox.isSelected());
        transferFunction2dButton.addActionListener(this::transferFunction2dButtonActionPerformed);

        jLabel7.setText("Front mode");
        jLabel7.setToolTipText("");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(renderingSpeedLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(shadingCheckbox)
                            .addComponent(cuttingPlaneCheckbox)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(compositingButton)
                                    .addComponent(tf2dButton)
                                    .addComponent(mipButton)
                                    .addComponent(slicerButton)
                                    .addComponent(isoSurfaceButton)
                                    .addComponent(jLabel7))
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IsovalueTextBox, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colorButton, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(slicerButton2)
                                    .addComponent(mipButton2)
                                    .addComponent(compositingButton2)
                                    .addComponent(isosurfaceButton2)
                                    .addComponent(transferFunction2dButton))
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IsovalueTextBox1, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(colorButton1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(renderingSpeedLabel))
                .addGap(18, 18, 18)
                .addComponent(shadingCheckbox)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuttingPlaneCheckbox)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slicerButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mipButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compositingButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(colorButton, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(isoSurfaceButton)
                            .addComponent(jLabel2)
                            .addComponent(IsovalueTextBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf2dButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(colorButton1, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slicerButton2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mipButton2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compositingButton2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(IsovalueTextBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(isosurfaceButton2))))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferFunction2dButton)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mipButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mipButtonActionPerformed
        renderer.setRaycastModeFront(RaycastMode.MIP);
        renderer.changed();
    }//GEN-LAST:event_mipButtonActionPerformed

    private void slicerButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_slicerButtonActionPerformed
        renderer.setRaycastModeFront(RaycastMode.SLICER);
        renderer.changed();
    }//GEN-LAST:event_slicerButtonActionPerformed

    private void compositingButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_compositingButtonActionPerformed
        renderer.setRaycastModeFront(RaycastMode.COMPOSITING);
        renderer.changed();
    }//GEN-LAST:event_compositingButtonActionPerformed

    private void tf2dButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_tf2dButtonActionPerformed
        renderer.setRaycastModeFront(RaycastMode.TRANSFER2D);
        renderer.changed();
    }//GEN-LAST:event_tf2dButtonActionPerformed

    private void shadingCheckboxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_shadingCheckboxActionPerformed
        renderer.setShadingMode(((JCheckBox) evt.getSource()).isSelected());
        renderer.changed();
    }//GEN-LAST:event_shadingCheckboxActionPerformed

    private void IsovalueTextBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_IsovalueTextBoxActionPerformed
        String s = this.IsovalueTextBox.getText();
        renderer.setIsoValueFront(Float.parseFloat(s));//set value
        renderer.changed();
    }//GEN-LAST:event_IsovalueTextBoxActionPerformed

    private void colorButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        // Change the color in the transfer function.
        Color newColor = JColorChooser.showDialog(this, "Choose color", colorButton.getBackground());
        if (newColor != null) {
            colorButton.setBackground(newColor);
            TFColor isoColor = new TFColor();
            isoColor.r = newColor.getRed() / 255.0;
            isoColor.g = newColor.getGreen() / 255.0;
            isoColor.b = newColor.getBlue() / 255.0;
            renderer.setIsoColorFront(isoColor);
            renderer.changed();
        }
    }//GEN-LAST:event_colorButtonActionPerformed

    private void isoSurfaceButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_isoSurfaceButtonActionPerformed
        renderer.setRaycastModeFront(RaycastMode.ISO_SURFACE);
        renderer.changed();
    }//GEN-LAST:event_isoSurfaceButtonActionPerformed

    private void cuttingPlaneCheckboxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cuttingPlaneCheckboxActionPerformed
        boolean selected = ((JCheckBox) evt.getSource()).isSelected();
        slicerButton2.setEnabled(selected);
        mipButton2.setEnabled(selected);
        compositingButton2.setEnabled(selected);
        isosurfaceButton2.setEnabled(selected);
        IsovalueTextBox1.setEnabled(selected);
        colorButton1.setEnabled(selected);
        transferFunction2dButton.setEnabled(selected);

        renderer.setCuttingPlaneMode(selected);
        renderer.changed();
    }//GEN-LAST:event_cuttingPlaneCheckboxActionPerformed

    private void IsovalueTextBox1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_IsovalueTextBox1ActionPerformed
        String s = this.IsovalueTextBox.getText();
        renderer.setIsoValueBack(Float.parseFloat(s));//set value
        renderer.changed();
    }//GEN-LAST:event_IsovalueTextBox1ActionPerformed

    private void colorButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_colorButton1ActionPerformed
        // Change the color in the transfer function.
        Color newColor = JColorChooser.showDialog(this, "Choose color", colorButton1.getBackground());
        if (newColor != null) {
            colorButton1.setBackground(newColor);
            TFColor isoColor = new TFColor();
            isoColor.r = newColor.getRed() / 255.0;
            isoColor.g = newColor.getGreen() / 255.0;
            isoColor.b = newColor.getBlue() / 255.0;
            renderer.setIsoColorBack(isoColor);
            renderer.changed();
        }
    }//GEN-LAST:event_colorButton1ActionPerformed

    private void slicerButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_slicerButton2ActionPerformed
        renderer.setRaycastModeBack(RaycastMode.INVISIBLE);
        renderer.changed();
    }//GEN-LAST:event_slicerButton2ActionPerformed

    private void mipButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mipButton2ActionPerformed
        renderer.setRaycastModeBack(RaycastMode.MIP);
        renderer.changed();
    }//GEN-LAST:event_mipButton2ActionPerformed

    private void compositingButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_compositingButton2ActionPerformed
        renderer.setRaycastModeBack(RaycastMode.COMPOSITING);
        renderer.changed();
    }//GEN-LAST:event_compositingButton2ActionPerformed

    private void isosurfaceButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_isosurfaceButton2ActionPerformed
        renderer.setRaycastModeBack(RaycastMode.ISO_SURFACE);
        renderer.changed();
    }//GEN-LAST:event_isosurfaceButton2ActionPerformed

    private void transferFunction2dButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_transferFunction2dButtonActionPerformed
        renderer.setRaycastModeBack(RaycastMode.TRANSFER2D);
        renderer.changed();
    }//GEN-LAST:event_transferFunction2dButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField IsovalueTextBox;
    private JTextField IsovalueTextBox1;
    private ButtonGroup buttonGroup1;
    private ButtonGroup buttonGroup2;
    private JButton colorButton;
    private JButton colorButton1;
    private JRadioButton compositingButton;
    private JRadioButton compositingButton2;
    private JCheckBox cuttingPlaneCheckbox;
    private JRadioButton isoSurfaceButton;
    private JRadioButton isosurfaceButton2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JRadioButton mipButton;
    private JRadioButton mipButton2;
    private JLabel renderingSpeedLabel;
    private JCheckBox shadingCheckbox;
    private JRadioButton slicerButton;
    private JRadioButton slicerButton2;
    private JRadioButton tf2dButton;
    private JRadioButton transferFunction2dButton;
    // End of variables declaration//GEN-END:variables
}
