/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;
import volvis.TFColor;
import volvis.TransferFunction;

/**
 *
 * @author michel
 */
public class TransferFunctionEditor extends JPanel {

    private TransferFunction tfunc;
    private TransferFunctionView tfView;
    private int selected;

    /**
     * Creates new form TransferFunctionEditor
     */
    public TransferFunctionEditor(TransferFunction tfunc, int[] histogram) {
        initComponents();

        this.tfunc = tfunc;
        this.tfView = new TransferFunctionView(tfunc, histogram, this);
        histogramPanel.setLayout(new BorderLayout());
        histogramPanel.add(tfView, BorderLayout.CENTER);
    }

    public void setSelectedInfo(int idx, int s, double a, TFColor c) {
        selected = idx;
        scalarTextField.setText(Integer.toString(s));
        opacityTextField.setText(String.format("%.2f", a));
        colorButton.setBackground(new Color((float) c.r, (float) c.g, (float) c.b));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        histogramPanel = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        scalarTextField = new JTextField();
        opacityTextField = new JTextField();
        jLabel4 = new JLabel();
        colorButton = new JButton();
        jPanel1 = new JPanel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();

        GroupLayout histogramPanelLayout = new GroupLayout(histogramPanel);
        histogramPanel.setLayout(histogramPanelLayout);
        histogramPanelLayout.setHorizontalGroup(
            histogramPanelLayout.createParallelGroup(GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        histogramPanelLayout.setVerticalGroup(
            histogramPanelLayout.createParallelGroup(GroupLayout.LEADING)
            .add(0, 254, Short.MAX_VALUE)
        );

        jLabel1.setText("Scalar value");

        jLabel2.setText("Opacity");

        jLabel3.setText("Color");

        scalarTextField.setEditable(false);
        scalarTextField.setHorizontalAlignment(JTextField.RIGHT);
        scalarTextField.setFocusTraversalKeysEnabled(false);
        scalarTextField.setFocusable(false);
        scalarTextField.setMaximumSize(new Dimension(84, 28));
        scalarTextField.setMinimumSize(new Dimension(84, 28));

        opacityTextField.setEditable(false);
        opacityTextField.setHorizontalAlignment(JTextField.RIGHT);
        opacityTextField.setToolTipText("");
        opacityTextField.setFocusTraversalKeysEnabled(false);
        opacityTextField.setFocusable(false);
        opacityTextField.setMaximumSize(new Dimension(84, 28));
        opacityTextField.setMinimumSize(new Dimension(84, 28));

        jLabel4.setText("Opacity");

        colorButton.setText("    ");
        colorButton.addActionListener(this::colorButtonActionPerformed);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.LEADING)
            .add(0, 299, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel5.setText("<html>Scalar value &rarr;</html>");

        jLabel6.setText("<html>&uarr;</html>");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel3, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                            .add(GroupLayout.TRAILING, jLabel2, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(GroupLayout.LEADING)
                            .add(scalarTextField, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .add(layout.createParallelGroup(GroupLayout.TRAILING, false)
                                .add(colorButton, GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .add(opacityTextField, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(jLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(GroupLayout.LEADING)
                            .add(histogramPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(jLabel5)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(histogramPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jLabel4)))
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jLabel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.RELATED)
                .add(layout.createParallelGroup(GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(scalarTextField, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(opacityTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(GroupLayout.BASELINE)
                            .add(jLabel3, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                            .add(colorButton)))
                    .add(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .add(0, 46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed

        Color newColor = JColorChooser.showDialog(this, "Choose color", colorButton.getBackground());
        if (newColor != null) {
            colorButton.setBackground(newColor);
            tfunc.updateControlPointColor(selected, newColor);
            tfunc.changed();
            tfView.repaint();
        }

    }//GEN-LAST:event_colorButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton colorButton;
    private JPanel histogramPanel;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPanel jPanel1;
    private JTextField opacityTextField;
    private JTextField scalarTextField;
    // End of variables declaration//GEN-END:variables
}
