/*
 * Anna Vilanova: Basic user interface for the raycaster. NO MODIFICATION NEEDED 
 *
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;

import util.TFChangeListener;
import volume.GradientVolume;
import volume.Volume;
import volume.VoxelGradient;
import volvis.TFColor;
import volvis.TransferFunction2D;

/**
 *
 * @author michel and modified by Anna Vilanova 
 * NO IMPLEMENTATION NEEDED FOR THE BASIC ASSIGNMENTME 
 * YOu need to modify it if you want to change the interface
 */
public class TransferFunction2DEditor extends JPanel {

    private Volume vol;
    private GradientVolume gradvol;
    public TransferFunction2D tf2D;
    private TransferFunction2DView tfView;
    public int xbins, ybins;
    public double[] histogram;
    private short maxIntensity;
    public double maxGradientMagnitude;
    private ArrayList<TFChangeListener> listeners = new ArrayList<>();

    
    public TransferFunction2DEditor(TransferFunction2D tf2D, Volume volume, GradientVolume gradientvolume) {
        initComponents();

        this.vol = volume;
        this.gradvol = gradientvolume;
        compute2Dhistogram();

        this.tfView = new TransferFunction2DView(this);
        plotPanel.setLayout(new BorderLayout());
        plotPanel.add(tfView, BorderLayout.CENTER);
        labelGradMin.setText("0.0");
        labelGradMax.setText(Double.toString(Math.floor(10 * maxGradientMagnitude) / 10));
        labelMinVal.setText("0");
        labelMaxVal.setText(Integer.toString(maxIntensity));

        // The initialization of the widget is at the center of the histogram and 20% of the intensity range
        this.tf2D = tf2D;
        tf2D.SetBaseRadius((short) (maxIntensity / 2), 0.2*maxIntensity);
        
        setSelectedInfo();
    }

    public void addTFChangeListener(TFChangeListener l) {
        if (!listeners.contains(l)) {
            listeners.add(l);
        }
    }

    public void changed() {
        for (TFChangeListener listener : listeners) {
            listener.changed();
        }
    }
    
    // Updates the histogram using the gradient
    private void compute2Dhistogram() {
        maxIntensity = vol.getMaximum();
        maxGradientMagnitude = gradvol.getMaxGradientMagnitude();

        System.out.println("maxIntensity = " + maxIntensity);
        System.out.println("max gradient = " + maxGradientMagnitude);

        xbins = maxIntensity + 1;
        ybins = 300;

        histogram = new double[xbins * ybins];
        int volumeSize = vol.getDimX() * vol.getDimY() * vol.getDimZ();
        for (int i = 0; i < volumeSize; i++) {
            short voxelVal = vol.getVoxel(i);
            VoxelGradient grad = gradvol.getVoxel(i);
            int yPos = (int) Math.floor(((ybins - 1) * grad.mag) / maxGradientMagnitude);
            histogram[yPos * xbins + voxelVal] += 1;
        }
    }

    public void setSelectedInfo() {
       /* intensityLabel.setText(Integer.toString(triangleWidget.baseIntensity));
        radiusLabel.setText(String.format("%.3f", triangleWidget.radius));
        opacityLabel.setText(String.format("%.1f", triangleWidget.color.a));
        colorButton.setBackground(new Color((float) triangleWidget.color.r, (float) triangleWidget.color.g, (float) triangleWidget.color.b));*/
        intensityLabel.setText(Integer.toString(tf2D.baseIntensity));
        radiusLabel.setText(String.format("%.3f", tf2D.radius));
        opacityLabel.setText(String.format("%.1f", tf2D.color.a));
        colorButton.setBackground(new Color((float) tf2D.color.r, (float) tf2D.color.g, (float) tf2D.color.b));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plotPanel = new JPanel();
        labelGradMax = new JLabel();
        labelGradMin = new JLabel();
        labelMinVal = new JLabel();
        labelMaxVal = new JLabel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        colorButton = new JButton();
        jLabel7 = new JLabel();
        opacityLabel = new JTextField();
        intensityLabel = new JTextField();
        radiusLabel = new JTextField();

        GroupLayout plotPanelLayout = new GroupLayout(plotPanel);
        plotPanel.setLayout(plotPanelLayout);
        plotPanelLayout.setHorizontalGroup(
            plotPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        plotPanelLayout.setVerticalGroup(
            plotPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        labelGradMax.setHorizontalAlignment(SwingConstants.RIGHT);
        labelGradMax.setText("jLabel1");

        labelGradMin.setHorizontalAlignment(SwingConstants.RIGHT);
        labelGradMin.setText("jLabel2");

        labelMinVal.setText("jLabel3");

        labelMaxVal.setHorizontalAlignment(SwingConstants.RIGHT);
        labelMaxVal.setText("jLabel4");

        jLabel1.setHorizontalAlignment(SwingConstants.LEFT);
        jLabel1.setText("Gradient");

        jLabel2.setText("magnitude");

        jLabel3.setText("Intensity");

        jLabel4.setText("Intensity");

        jLabel5.setText("Opacity");

        jLabel6.setText("Color");

        colorButton.setBounds(new Rectangle(0, 0, 75, 29));
        colorButton.addActionListener(this::colorButtonActionPerformed);

        jLabel7.setText("Radius");

        opacityLabel.setText("jTextField2");
        opacityLabel.setMinimumSize(new Dimension(84, 28));
        opacityLabel.addActionListener(this::opacityLabelActionPerformed);

        intensityLabel.setEditable(false);
        intensityLabel.setText("jTextField1");
        intensityLabel.setMinimumSize(new Dimension(84, 28));

        radiusLabel.setEditable(false);
        radiusLabel.setText("jTextField3");
        radiusLabel.setMinimumSize(new Dimension(84, 28));

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE))
                        .addComponent(labelGradMin, GroupLayout.Alignment.TRAILING)
                        .addComponent(labelGradMax, GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(labelMinVal)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(opacityLabel, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(intensityLabel, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)))
                            .addComponent(colorButton, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelMaxVal)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiusLabel, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plotPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelGradMax)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelGradMin))
                    .addComponent(plotPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(labelMaxVal, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(labelMinVal))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(intensityLabel, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(radiusLabel, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(opacityLabel, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(colorButton, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        // Change the color in the transfer function.
        Color newColor = JColorChooser.showDialog(this, "Choose color", colorButton.getBackground());
        if (newColor != null) {
            colorButton.setBackground(newColor);
            tf2D.color.r = newColor.getRed() / 255.0;
            tf2D.color.g = newColor.getGreen() / 255.0;
            tf2D.color.b = newColor.getBlue() / 255.0;
            
            changed();
        }
    }//GEN-LAST:event_colorButtonActionPerformed

    private void opacityLabelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_opacityLabelActionPerformed
       try {
            double value = Double.parseDouble(opacityLabel.getText());
            if (value < 0) {
                value = 0;
            } 
            if (value > 1.0) {
                value = 1.0;
            }
            tf2D.color.a = value;
        } catch (NumberFormatException e) {
            tf2D.color.a = 0.2;
        }
        setSelectedInfo();
        changed();
    }//GEN-LAST:event_opacityLabelActionPerformed

/*    public class TriangleWidget {

        public short baseIntensity;
        public double radius;
        public TFColor color;
        

        public TriangleWidget(short base, double r) {
            this.baseIntensity = base;
            this.radius = r;
            this.color = new TFColor(0.0, 204.0/255.0, 153.0/255.0, 0.3);
        }
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton colorButton;
    private JTextField intensityLabel;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel labelGradMax;
    private JLabel labelGradMin;
    private JLabel labelMaxVal;
    private JLabel labelMinVal;
    private JTextField opacityLabel;
    private JPanel plotPanel;
    private JTextField radiusLabel;
    // End of variables declaration//GEN-END:variables
}
